[build]
  command = "npm run build --prefix next-client"
  publish = "next-client/out"

[build.environment]
  NEXT_PUBLIC_FORCE_LOCAL_STORAGE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
